if not gg then
  print("This script must run inside GameGuardian")
  os.exit()
end

---------- CONFIGURATION ----------
-- Di sini Anda bisa menambahkan signature (AOB) baru
local SIGNATURE_LIBRARY = {
  {
    name = "Anti-Cheat Initializer",
    pattern = "h 00 00 A0 E3 1E FF 2F E1", -- Contoh signature ARM
    type = gg.TYPE_DWORD,
    region = gg.REGION_CODE_APP
  },
  {
    name = "Security Flag Monitor",
    pattern = "0;0;0;1;0;0:17", -- Contoh group search GG
    type = gg.TYPE_DWORD,
    region = gg.REGION_ANONYMOUS
  }
}

---------- UTILITIES ----------
local function hex(value)
  if value == nil then return "N/A" end
  return string.format("0x%X", value)
end

---------- SCANNING LOGIC ----------

local function performAutoScan()
  gg.clearResults()
  local foundCodes = {}

  for _, sig in ipairs(SIGNATURE_LIBRARY) do
    gg.toast("Scanning for: " .. sig.name)
    gg.setRanges(sig.region)

    -- Menggunakan API standar GG untuk pencarian
    -- Catatan: h menunjukkan hex, ; menunjukkan group search
    gg.searchNumber(sig.pattern, sig.type)

    local count = gg.getResultsCount()
    if count > 0 then
      local results = gg.getResults(5) -- Ambil 5 hasil pertama
      table.insert(foundCodes, {
        name = sig.name,
        addresses = results,
        count = count
      })
      gg.toast("✅ Found " .. count .. " matches for " .. sig.name)
    else
      gg.toast("❌ No match for " .. sig.name)
    end

    gg.clearResults() -- Bersihkan untuk scan berikutnya
  end

  return foundCodes
end

local function generateCodeSnippet(foundCodes)
  if #foundCodes == 0 then
    gg.alert("Tidak ada kode yang ditemukan untuk dibuatkan snippet.")
    return
  end

  local code = "-- Auto-Generated Bypass Code Snippet\n\n"
  for _, item in ipairs(foundCodes) do
    code = code .. "-- Pattern: " .. item.name .. "\n"
    for i, res in ipairs(item.addresses) do
      code = code .. string.format("local addr_%d = %s\n", i, hex(res.address))
      code = code .. string.format("gg.setValues({{address = addr_%d, flags = %d, value = 0}}) -- Edit to 0\n", i, res.flags)
    end
    code = code .. "\n"
  end

  gg.copyText(code)
  gg.alert("Snippet kode telah disalin ke clipboard!\n\n" .. code)
end

---------- MAIN MENU ----------
local function showMainMenu()
  local menu = {
    "🔍 Mulai Auto-Scan Signature",
    "📝 Edit Signature Library (Instruksi)",
    "⚙️ Pengaturan Region",
    "🚪 Keluar"
  }

  while true do
    local choice = gg.choice(menu, nil, "🤖 AUTOMATED SIGNATURE SCANNER V1.0")

    if not choice or choice == 4 then break end

    if choice == 1 then
      local results = performAutoScan()
      if #results > 0 then
        local report = "Hasil Scan:\n"
        for _, r in ipairs(results) do
          report = report .. string.format("- %s: %d matches\n", r.name, r.count)
        end
        gg.alert(report)

        local subChoice = gg.choice({"📋 Salin Kode Snippet", "🔙 Kembali"}, nil, "Aksi Lanjutan")
        if subChoice == 1 then
          generateCodeSnippet(results)
        end
      else
        gg.alert("Scan selesai. Tidak ada signature yang cocok ditemukan.")
      end

    elseif choice == 2 then
      gg.alert([[📖 CARA MENGEDIT SIGNATURE:

1. Buka file script ini di text editor.
2. Cari bagian 'SIGNATURE_LIBRARY'.
3. Tambahkan baris baru dengan format:
   {
     name = "Nama Mod Anda",
     pattern = "HEX_ATAU_ANGKA",
     type = gg.TYPE_XXX,
     region = gg.REGION_XXX
   }
4. Gunakan 'h' di depan pattern untuk HEX (misal: "h 01 02 03").
5. Gunakan ';' untuk group search (misal: "100;200;300").]])

    elseif choice == 3 then
      gg.alert("Gunakan menu ini untuk mengubah region default jika diperlukan. Saat ini script menggunakan region yang ditentukan di tiap signature.")
    end
  end
end

---------- INITIALIZATION ----------
gg.toast("🤖 Automated Scanner Ready!")
showMainMenu()
